#
# GNUmakefile - Generated by ProjectCenter
#
ifeq ($(GNUSTEP_MAKEFILES),)
 GNUSTEP_MAKEFILES := $(shell gnustep-config --variable=GNUSTEP_MAKEFILES 2>/dev/null)
  ifeq ($(GNUSTEP_MAKEFILES),)
    $(warning )
    $(warning Unable to obtain GNUSTEP_MAKEFILES setting from gnustep-config!)
    $(warning Perhaps gnustep-make is not properly installed,)
    $(warning so gnustep-config is not in your PATH.)
    $(warning )
    $(warning Your PATH is currently $(PATH))
    $(warning )
  endif
endif
ifeq ($(GNUSTEP_MAKEFILES),)
 $(error You need to set GNUSTEP_MAKEFILES before compiling!)
endif

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 0.1
PACKAGE_NAME = Weather
APP_NAME = Weather
Weather_APPLICATION_ICON = 


#
# Libraries
#
Weather_LIBRARIES_DEPEND_UPON += -lWebServices 

#
# Resource files
#
Weather_RESOURCE_FILES = \
Resources/Weather.gorm \


#
# Header files
#
Weather_HEADER_FILES = \
AppController.h \
LocationWeatherData.h \
WeatherApi.h

#
# Objective-C Class files
#
Weather_OBJC_FILES = \
AppController.m \
LocationWeatherData.m \
WeatherApi.m

#
# Other sources
#
Weather_OBJC_FILES += \
Weather_main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
